---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rco-frozenbits-se-v1alpha1-rcloneclusterremote
  failurePolicy: Fail
  name: vrcloneclusterremote-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rco.frozenbits.se
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rcloneclusterremotes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rco-frozenbits-se-v1alpha1-rcloneremote
  failurePolicy: Fail
  name: vrcloneremote-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rco.frozenbits.se
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rcloneremotes
  sideEffects: None
