---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - rco.frozenbits.se
  resources:
  - rcloneclusterremotes
  - rcloneremotes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rco.frozenbits.se
  resources:
  - rcloneclusterremotes/status
  - rcloneremotes/status
  verbs:
  - get
  - patch
  - update
