apiVersion: rco.frozenbits.se/v1alpha1
kind: RCloneRemote
metadata:
  labels:
    app.kubernetes.io/name: rclone-operator
    app.kubernetes.io/managed-by: kustomize
  name: rcloneremote-sample
spec:
  # TODO(user): Add fields here
