//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptBackend) DeepCopyInto(out *CryptBackend) {
	*out = *in
	out.RemoteRef = in.RemoteRef
	out.PasswordRef = in.PasswordRef
	if in.SaltRef != nil {
		in, out := &in.SaltRef, &out.SaltRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.DirectoryNameEncryption != nil {
		in, out := &in.DirectoryNameEncryption, &out.DirectoryNameEncryption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptBackend.
func (in *CryptBackend) DeepCopy() *CryptBackend {
	if in == nil {
		return nil
	}
	out := new(CryptBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCloneClusterRemote) DeepCopyInto(out *RCloneClusterRemote) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCloneClusterRemote.
func (in *RCloneClusterRemote) DeepCopy() *RCloneClusterRemote {
	if in == nil {
		return nil
	}
	out := new(RCloneClusterRemote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCloneClusterRemote) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCloneClusterRemoteList) DeepCopyInto(out *RCloneClusterRemoteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RCloneClusterRemote, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCloneClusterRemoteList.
func (in *RCloneClusterRemoteList) DeepCopy() *RCloneClusterRemoteList {
	if in == nil {
		return nil
	}
	out := new(RCloneClusterRemoteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCloneClusterRemoteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCloneRemote) DeepCopyInto(out *RCloneRemote) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCloneRemote.
func (in *RCloneRemote) DeepCopy() *RCloneRemote {
	if in == nil {
		return nil
	}
	out := new(RCloneRemote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCloneRemote) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCloneRemoteList) DeepCopyInto(out *RCloneRemoteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RCloneRemote, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCloneRemoteList.
func (in *RCloneRemoteList) DeepCopy() *RCloneRemoteList {
	if in == nil {
		return nil
	}
	out := new(RCloneRemoteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCloneRemoteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCloneRemoteSpec) DeepCopyInto(out *RCloneRemoteSpec) {
	*out = *in
	if in.SFTP != nil {
		in, out := &in.SFTP, &out.SFTP
		*out = new(SftpBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.Crypt != nil {
		in, out := &in.Crypt, &out.Crypt
		*out = new(CryptBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Backend)
		(*in).DeepCopyInto(*out)
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(TemplateBackend)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCloneRemoteSpec.
func (in *RCloneRemoteSpec) DeepCopy() *RCloneRemoteSpec {
	if in == nil {
		return nil
	}
	out := new(RCloneRemoteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCloneRemoteStatus) DeepCopyInto(out *RCloneRemoteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCloneRemoteStatus.
func (in *RCloneRemoteStatus) DeepCopy() *RCloneRemoteStatus {
	if in == nil {
		return nil
	}
	out := new(RCloneRemoteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteRef) DeepCopyInto(out *RemoteRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteRef.
func (in *RemoteRef) DeepCopy() *RemoteRef {
	if in == nil {
		return nil
	}
	out := new(RemoteRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Backend) DeepCopyInto(out *S3Backend) {
	*out = *in
	out.AccessKeyIDRef = in.AccessKeyIDRef
	out.SecretAccessKeyRef = in.SecretAccessKeyRef
	if in.ForcePathStyle != nil {
		in, out := &in.ForcePathStyle, &out.ForcePathStyle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Backend.
func (in *S3Backend) DeepCopy() *S3Backend {
	if in == nil {
		return nil
	}
	out := new(S3Backend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SftpBackend) DeepCopyInto(out *SftpBackend) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.PrivateKeyPassphraseRef != nil {
		in, out := &in.PrivateKeyPassphraseRef, &out.PrivateKeyPassphraseRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SftpBackend.
func (in *SftpBackend) DeepCopy() *SftpBackend {
	if in == nil {
		return nil
	}
	out := new(SftpBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateBackend) DeepCopyInto(out *TemplateBackend) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]SecretKeyRef, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateBackend.
func (in *TemplateBackend) DeepCopy() *TemplateBackend {
	if in == nil {
		return nil
	}
	out := new(TemplateBackend)
	in.DeepCopyInto(out)
	return out
}
